### ISSUE TITLE
How to handle the click of Native Ad

### ISSUE THREAD

**Issue by jinguoliang** [binishmanandhar23/AdMobInCompose#1]
Now， when click the native ad，it has no response

**Comment by binishmanandhar23** [comment]
The click listener is handle by Google's AdMob library, we have no control over it.
Make sure to properly initialize all of the views of a NativeAdView (for example: headlineView, bodyView, etc.).
If that doesn't help then go through my demo code that I've used to demonstrate the library's functionality.
Linked here:
[MainActivity.kt](https://github.com/binishmanandhar23/AdMobInCompose/blob/main/app/src/main/java/io/github/binishmanandhar23/admobincomposeexample/MainActivity.kt)
